server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    discovery:
      reactive:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true

      defaultFilters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalCors:
        corsConfigurations:
          '[/**]':
              allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:58632"
              - "https://p3solutions-main.azurewebsites.net"
              - "https://p3solutions-cliclogistic.azurewebsites.net"
              - "https://p3solutions-meals.azurewebsites.net"
              allowedMethods:
              - POST
              - GET
              - PUT
              allowedHeaders: "*"
              allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/main/**
          filters:
            AuthFilter
        - id: cliclogistic-service
          uri: lb://cliclogistic-service
          predicates:
            - Path=/cliclogistic/**
          filters:
            AuthFilter
        - id: meals-service
          uri: lb://meals-service
          predicates:
            - Path=/meals/**
          filters:
            AuthFilter