server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost:4200

spring:
  cloud:
    discovery:
      reactive:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/main/**
          filters:
            AuthFilter
        - id: cliclogistic-service
          uri: lb://cliclogistic-service
          predicates:
            - Path=/cliclogistic/**
          filters:
            AuthFilter
        - id: meals-service
          uri: lb://meals-service
          predicates:
            - Path=/meals/**
          filters:
            AuthFilter